import type { Property } from '../types'

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'mock-001',
    owner_id: 'owner-001',
    name: 'Casa de Praia em Florianópolis',
    description: 'Linda casa com vista para o mar, piscina e churrasqueira. Perfeita para famílias.',
    type: 'CASA',
    status: 'ATIVO',
    plan: 'DESTAQUE',
    city: 'Florianópolis',
    state: 'SC',
    neighborhood: 'Jurerê Internacional',
    address: null,
    cep: null,
    number: null,
    complement: null,
    country: 'Brasil',
    latitude: -27.4396,
    longitude: -48.4936,
    price_per_night: 850,
    min_price: 600,
    bedrooms: 4,
    bathrooms: 3,
    max_guests: 10,
    amenities: ['Piscina', 'Churrasqueira', 'Wi-Fi', 'Ar-condicionado', 'Estacionamento'],
    photos: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
    ],
    cancellation_policy: 'MODERADO',
    rating: 4.9,
    reviews_count: 47,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-002',
    owner_id: 'owner-002',
    name: 'Chalé nas Montanhas de Gramado',
    description: 'Chalé aconchegante com lareira, banheira de hidromassagem e vista para a serra.',
    type: 'CHALÉ',
    status: 'ATIVO',
    plan: 'STANDARD',
    city: 'Gramado',
    state: 'RS',
    neighborhood: 'Centro',
    address: null,
    cep: null,
    number: null,
    complement: null,
    country: 'Brasil',
    latitude: -29.3742,
    longitude: -50.8764,
    price_per_night: 420,
    min_price: 300,
    bedrooms: 2,
    bathrooms: 2,
    max_guests: 4,
    amenities: ['Jacuzzi', 'Wi-Fi', 'Fogueira', 'TV a cabo', 'Cozinha equipada'],
    photos: [
      'https://images.unsplash.com/photo-1464278533981-50106e6176b1?w=800',
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800',
    ],
    cancellation_policy: 'FIRME',
    rating: 4.8,
    reviews_count: 32,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-003',
    owner_id: 'owner-003',
    name: 'Cobertura Luxuosa em Ipanema',
    description: 'Cobertura duplex com terraço, piscina privativa e vista panorâmica para o mar.',
    type: 'COBERTURA',
    status: 'ATIVO',
    plan: 'DESTAQUE',
    city: 'Rio de Janeiro',
    state: 'RJ',
    neighborhood: 'Ipanema',
    address: null,
    cep: null,
    number: null,
    complement: null,
    country: 'Brasil',
    latitude: -22.9839,
    longitude: -43.1956,
    price_per_night: 1800,
    min_price: 1400,
    bedrooms: 3,
    bathrooms: 4,
    max_guests: 6,
    amenities: ['Piscina', 'Wi-Fi', 'Ar-condicionado', 'Academia', 'Segurança 24h'],
    photos: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    ],
    cancellation_policy: 'FIRME',
    rating: 5.0,
    reviews_count: 18,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-004',
    owner_id: 'owner-001',
    name: 'Sítio com Cachoeira em Bonito',
    description: 'Sítio com acesso à cachoeira, trilhas e muito contato com a natureza.',
    type: 'SÍTIO',
    status: 'ATIVO',
    plan: 'STANDARD',
    city: 'Bonito',
    state: 'MS',
    neighborhood: null,
    address: null,
    cep: null,
    number: null,
    complement: null,
    country: 'Brasil',
    latitude: -21.1256,
    longitude: -56.4874,
    price_per_night: 290,
    min_price: 220,
    bedrooms: 3,
    bathrooms: 2,
    max_guests: 8,
    amenities: ['Churrasqueira', 'Piscina', 'Estacionamento', 'Permitido pets'],
    photos: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
      'https://images.unsplash.com/photo-1615729947596-a598e5de0ab3?w=800',
    ],
    cancellation_policy: 'LEVE',
    rating: 4.7,
    reviews_count: 24,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-005',
    owner_id: 'owner-002',
    name: 'Apartamento Moderno em São Paulo',
    description: 'Studio moderno na Vila Madalena, próximo a restaurantes, bares e metrô.',
    type: 'STUDIO',
    status: 'ATIVO',
    plan: 'STANDARD',
    city: 'São Paulo',
    state: 'SP',
    neighborhood: 'Vila Madalena',
    address: null,
    cep: null,
    number: null,
    complement: null,
    country: 'Brasil',
    latitude: -23.5506,
    longitude: -46.6903,
    price_per_night: 180,
    min_price: 150,
    bedrooms: 1,
    bathrooms: 1,
    max_guests: 2,
    amenities: ['Wi-Fi', 'Ar-condicionado', 'TV a cabo', 'Lavanderia'],
    photos: [
      'https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800',
    ],
    cancellation_policy: 'LEVE',
    rating: 4.6,
    reviews_count: 61,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-006',
    owner_id: 'owner-003',
    name: 'Pousada à Beira-Mar em Porto de Galinhas',
    description: 'Pousada charmosa com piscina natural e café da manhã incluso.',
    type: 'POUSADA',
    status: 'ATIVO',
    plan: 'DESTAQUE',
    city: 'Ipojuca',
    state: 'PE',
    neighborhood: 'Porto de Galinhas',
    address: null,
    cep: null,
    number: null,
    complement: null,
    country: 'Brasil',
    latitude: -8.6686,
    longitude: -35.0032,
    price_per_night: 390,
    min_price: 300,
    bedrooms: 2,
    bathrooms: 2,
    max_guests: 4,
    amenities: ['Piscina', 'Churrasqueira', 'Wi-Fi', 'Ar-condicionado'],
    photos: [
      'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800',
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
    ],
    cancellation_policy: 'MODERADO',
    rating: 4.8,
    reviews_count: 39,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
